### PR TITLE
Allow to have the fade-in effect only on main page

### PR DESCRIPTION
**Pull request by er-vin**

### CODE REVIEW

**Comment by Hanzei** [comment]
Why do you thing this change is needed?

**Comment by Hanzei** [comment]
@er-vin I agree with you. The fade effect is nice on the home page but unnecessary on content page. I propose to only use it on the main page and don't add a config option for this.

**Comment by vickylai** [comment]
I'd prefer a config option, as not all users may have only the first page as a landing page. Otherwise :+1:

**Comment by Hanzei** [comment]
@er-vin Would you give this a rebase?

**Comment by er-vin** [comment]
Sure, would gladely give it a shot, I'm super busy work wise for the coming two week though, so please be a bit patient.

**Comment by er-vin** [comment]
Alright, now rebased.

Man... porting my website to the new master isn't a walk in the park, still have a couple of things broken. I guess you can expect a couple more pull requests. ;-)

**Comment by hanzei** [comment]
Thank you @er-vin for the contribution!

**Pull request merged**
