### PR TITLE
Also add regular font awesome to the css

### PR DESCRIPTION
**Pull request by er-vin**

### CODE REVIEW

**Comment by hanzei** [comment]
Why is this needed? I think fa regular is not used in the theme. This changes just makes the css bundle bigger.

**Comment by er-vin** [comment]
I use it in my home page, should I proceed differently to make sure it's pulled?

**Comment by hanzei** [comment]
You can just override the themes `_fontawesome-import.sass` by providing your own file at `assets/sass/_fontawesome-import.sass`

**Comment by er-vin** [comment]
Oh right, of course... stupid me...

**Pull request closed without merging**
