### PR TITLE
Update docs & Add script to build docs

### PR DESCRIPTION
**Pull request by hanzei**
Related to #85

### CODE REVIEW

**Comment by hanzei** [comment]
@vickylai Could you please run `./scripts/build_docs.sh` and check if you get the same `docs/` folder then me?

**Comment by vickylai** [comment]
Yes it seems to be the same.

**Comment by hanzei** [comment]
Great! Could we merge this one to test out if it fixes the problem with https://vickylai.com/hugo-theme-introduction/?

**Comment by hanzei** [comment]
@vickylai Did you revert this PR? It doesn't show up on master, see https://github.com/vickylai/hugo-theme-introduction/commits/master.

**Comment by hanzei** [comment]
Something is messed up with the git history. https://github.com/vickylai/hugo-theme-introduction/pull/95 is also missing on `master`. Did you force push something?

**Comment by vickylai** [comment]
@hanzei My bad. Fixed it and the assets seem to load properly now! :champagne:

**Pull request merged**
