### PR TITLE
Serve hugo pipes assets with .RelPermalink

### LINKED ISSUE #85: Assets not loading when root domain includes path?
I've set up `docs/` as the demo site, generated from the `exampleSite/` folder with:

```
hugo --themesDir ../.. -d ../docs 
```

It seems that no assets load at https://vickylai.com/hugo-theme-introduction/ unless (as a bandaid solution) I also include:

```
--baseURL https://vickylai.com/hugo-theme-introduction/
```

In which case the css loads, but none of the fonts.

Is this related to `assets/sass/style.sass` font paths?

### LINKED ISSUE #106: The Theme's Demo on the Hugo Website is missing its Hugo Pipes Assets
Hi @vickylai 

On the Hugo Themes website the [demo](https://themes.gohugo.io/theme/hugo-theme-introduction/) of the [Hugo Theme Introduction](https://themes.gohugo.io/hugo-theme-introduction/) has its Hugo Pipes Assets missing. 

To fix this issue please see the [Common Permalink Issues](https://github.com/gohugoio/hugoThemes#common-permalink-issues) in the updated README of the Hugo Themes repository.

>If you are using Hugo Pipes to publish your theme's resources you need to use `.RelPermalink` in the templates, so that these assets are served correctly on the website.

For example change line 11 of `/layouts/partials/base/imports.html/` to:
`<link rel="stylesheet" href="{{ $bundle.RelPermalink }}" integrity="{{ $bundle.Data.Integrity }}" media="screen">`

and line 17 to:
`<link rel="stylesheet" href="{{ $style.RelPermalink }}" integrity="{{ $style.Data.Integrity }}" media="screen">`

You need to do this change for every Hugo Pipes Asset that is used in your theme's templates.

Please do this change and let me know.

Thanks!

CC / @digitalcraftsman

### PR DESCRIPTION
**Pull request by hanzei**
Fixes #85 
Fixes #106

### CODE REVIEW

**Comment by onedrawingperday** [comment]
@vickylai @hanzei Any updates on this PR? The Introduction Theme is currently the only theme on the Hugo website with missing CSS in its demo: https://themes.gohugo.io/theme/hugo-theme-introduction/

**Comment by hanzei** [comment]
I've merged this PR. Hope you don't mind @vickylai 

@onedrawingperday Once this theme gets updated, the demo site should be fixed.

**Comment by onedrawingperday** [comment]
@hanzei You also need to Regenerate the Theme's Assets and commit them in the repository. 

Thanks!

**Comment by onedrawingperday** [comment]
@hanzei I just tested with the updated theme with the Themes Site Build Script and now the main CSS loads. 

However `fontawesome` icons are still missing. I will investigate further and open a separate issue about the missing icon font.

**Comment by hanzei** [comment]
Thanks @onedrawingperday!

**Pull request merged**
