### PR TITLE
Adds translation to the Twitter share text

### PR DESCRIPTION
**Pull request by emembrives**
This branch is based on my other pull request (due to the base French translation), but it is a somewhat independent bug fix.

### CODE REVIEW

**Comment by hanzei** [comment]
Thanks for the contribution, good catch!

But I would rather remove the language depended text in the twitter share text. This would also make it consistent with the other share texts.

Would you like to provide a fix for this?

**Comment by emembrives** [comment]
Sure, I'll do that.

**Comment by emembrives** [comment]
You can review now :-)

**Comment by hanzei** [comment]
Thanks @emembrives!

**Pull request merged**
